# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='created_at',
            new_name='date',
        ),
    ]
